### ISSUE TITLE
[To-Do] Boosted Creature

### ISSUE THREAD

**Issue by ghost** [opentibiabr/otservbr-global-archived#330]
With every server save, a randomly drawn creature will receive a temporary boost until next server save. During that time, the selected creature will:

- [x] the list of creatures that can be picked is the same of prey lists
- [x] yield more experience points (double the normal amount).
- [x] carry more loot than usual (double the normal amount).
- [x] respawn at a faster rate (two times faster respawn rate than usual).
- [x] The currently boosted creature will be displayed on the login screen of the client
- [x] Add talk action to GODs to select a specific monster or set a random one
- [x] message on login:

20:06 Your last visit in Tibia: 27. Jul 2019 09:00:45 CEST.
**20:06 Today's boosted creature: Orc Spearman
Boosted creatures yield more experience points, carry more loot than usual and respawn at a faster rate.**
20:06 Due to your long-term loyalty to Tibia, you currently benefit from a 5 % bonus on all of your skills.

![2019-07-29 20_07_37-Window](https://user-images.githubusercontent.com/4684880/62088680-8c1cf280-b23c-11e9-9e2b-1a4994d636dd.jpg)

**Comment by majestyotbr** [comment]
https://github.com/opentibiabr/otservbr-global/commit/7abcf8f8a4a485a143bae21e22db7c7316d114f6
