### ISSUE TITLE
[to-do] memorial (golden outfit)

### ISSUE THREAD

**Issue by ghost** [opentibiabr/otservbr-global-archived#366]
We currently lack the memorial script:

- [x] add the outfit and addon to King Tibianus, Queen Eloise and Emperor Kruzak ([transcripts](https://tibia.fandom.com/wiki/Golden_Outfits_Quest/Spoiler))
- [x] add the respective 'golden outfit display' that should be obtained with each part of outfit (itemID 36345 for base outfit, 36341 for helmet addon, 36337 for boots, 36349 for full outfit )
- [x] need to edit NPCs to ask the player for the former outfit display, in order to delete it and give the new one, so the player doesn't end up with 4 displays on his house
- [x] add some sort of storage to detect each player that has obtained full outfit (not only wearing it)
- [x] add the script to list the players in the way shown bellow, if no one have it just display "The Golden Outfit has not been acquired by anyone yet."

data/actions/scripts/others/variables/goldenOutfitMemorial.lua

```
The following characters have spent a fortune on a Golden Outfit:

Full Outfit for 1,000,000,000 gold:
- Character name 1
- Character name 2
- Character name 3
- Character name 4
- Character name 5
- etc
```

**Comment by gpedro** [comment]
reject donation
```
01:14 King Tibianus: I greet thee, my loyal subject Ellocer.
01:14 Ellocer [75]: addon
01:14 King Tibianus: In exchange for a truly generous donation, I will offer a special outfit. Do you want to make a donation?
01:14 Ellocer [75]: no
01:14 King Tibianus: Hm, I see.
(leave)
```

accept donation and try get boots without armor
```
01:15 Ellocer [75]: hello king
01:15 King Tibianus: I greet thee, my loyal subject Ellocer.
01:15 Ellocer [75]: addon
01:15 King Tibianus: In exchange for a truly generous donation, I will offer a special outfit. Do you want to make a donation?
01:15 Ellocer [75]: yes
01:15 King Tibianus: Excellent! Now, let me explain. If you donate 1.000.000.000 gold pieces, you will be entitled to wear a unique outfit. ...
01:15 King Tibianus: You will be entitled to wear the armor for 500.000.000 gold pieces, boots for an additional 250.000.000 and the helmet for another 250.000.000 gold pieces. ...
01:15 King Tibianus: What will it be?
01:15 Ellocer [75]: boots
01:15 King Tibianus: So you would like to donate 250.000.000 gold pieces which in return will entitle you to wear unique boots?
01:15 Ellocer [75]: yes
01:15 King Tibianus: I am sorry but are not yet entitled to wear the armor.
(reset)
```

accept donation, accept boots, reject donation
```
01:16 Ellocer [75]: addon
01:16 King Tibianus: In exchange for a truly generous donation, I will offer a special outfit. Do you want to make a donation?
01:16 Ellocer [75]: yes
01:16 King Tibianus: Excellent! Now, let me explain. If you donate 1.000.000.000 gold pieces, you will be entitled to wear a unique outfit. ...
01:16 King Tibianus: You will be entitled to wear the armor for 500.000.000 gold pieces, boots for an additional 250.000.000 and the helmet for another 250.000.000 gold pieces. ...
01:16 King Tibianus: What will it be?
01:16 Noodles: Grrrr!
01:16 Ellocer [75]: boots
01:16 King Tibianus: So you would like to donate 250.000.000 gold pieces which in return will entitle you to wear unique boots?
01:16 Ellocer [75]: no
01:16 King Tibianus: Very well, alright then.
(leave)
```

**Comment by gpedro** [comment]
empty memorial
``` 
The Golden Outfit has not been acquired by anyone yet.
````

**Comment by majestyotbr** [comment]
https://github.com/opentibiabr/OTServBR-Global/commit/7728e13a77aa44d37eead41eb9a4ae6ae6271c58
