### ISSUE TITLE
[to-do] 12.20 update things

### ISSUE THREAD

**Issue by FakeShinoda** [opentibiabr/otservbr-global-archived#485]
**MAP**
- [x] Kilmaresh 
- [ ] Cobra Bastion 95%
- [ ] Grave Danger Quest Areas 80%

**NPC's**
- [x] **Alyxo** -- Few missions of [Kilmaresh Quest](https://www.tibiawiki.com.br/wiki/Kilmaresh_Quest)
- [x] **Ambassador Of Rathleton** -- Just roleplay 
- [x] **Atur** -- Bank NPC
- [x] **Captain Harava** -- Travel to Oramond, Krailos, Venore e Darashia
- [x] **Eliyas** -- Distance weapons seller
- [x] **Eshaya** -- Begins of [Kilmaresh Quest](https://www.tibiawiki.com.br/wiki/Kilmaresh_Quest),
- [x] **Faloriel** -- Only sell potions
- [x] **Guard Bazaya** -- Just roleplay topics, and needed to pay the 1k fee if you killed a sheep
- [x] **Guard Inurta** -- Just roleplay topics, and needed to pay the 1k fee if you killed a sheep
- [x] **Guard Saros** -- Just roleplay topics, and needed to pay the 1k fee if you killed a sheep
- [x] **Guard Senet** -- Just roleplay topics, and needed to pay the 1k fee if you killed a sheep
- [x] **Guide Meruka** -- Defalut tibia guide
- [x] **Iptar-Sin** -- Just roleplay
- [x] **Kallimae** -- Part of [Kilmaresh Quest](https://www.tibiawiki.com.br/wiki/Kilmaresh_Quest)
- [x] **Khanna** -- Seller of runes, Wands/Rods, Exercise Wand/Rod, life ring and crystal ball
- [x] **Moe** -- Few missions of [Kilmaresh Quest](https://www.tibiawiki.com.br/wiki/Kilmaresh_Quest)
- [x] **Narsai** -- Few missions of [Kilmaresh Quest](https://www.tibiawiki.com.br/wiki/Kilmaresh_Quest)
- [x] **Ninev** -- Few missions of [Kilmaresh Quest](https://www.tibiawiki.com.br/wiki/Kilmaresh_Quest)
- [x] **Ninos** -- Postman NPC [letter, parcel e label]
- [x] **Ramina** -- Food Seller [**Food List**](https://www.tibiawiki.com.br/wiki/Ramina)
- [x] **Tamed Lion** --  Does nothing just "**Grrr!** when "hi" to him.
- [x] **Tanyt** -- Magic Carpet to _Darashia_, _Svargrond_, _Kazordoon_, _Zao_, _Femor Hills_ or _Edron_
- [x] **The Empress** -- Few missions of [Kilmaresh Quest](https://www.tibiawiki.com.br/wiki/Kilmaresh_Quest) 
- [x] **The Librarian** -- [Buy/Sell](http://prntscr.com/oysf9e) books and have missions of [Kilmaresh Quest](https://www.tibiawiki.com.br/wiki/Kilmaresh_Quest) 
- [x] **Yonan** -- Buy/Sell Jewellery
- [x] **Inkaef** -- Furniture Seller
- [x] **Saideh** -- Mission [The Revenge of the Ogres](https://www.tibiawiki.com.br/wiki/Kilmaresh_Quest#The_Revenge_of_the_Ogres) of Kilmaresh Quest
- [x] **Shimun** -- Diversas missões da [Kilmaresh Quest](https://www.tibiawiki.com.br/wiki/Kilmaresh_Quest)
- [x] **Tefrit** -- Few missions of  [Kilmaresh Quest](https://www.tibiawiki.com.br/wiki/Kilmaresh_Quest)
- [x] **Jack Springer** -- Entire [Grave Danger Quest](https://www.tibiawiki.com.br/wiki/Grave_Danger_Quest)

**QUESTS**
- [ ] **Kilmaresh Quest** -- [Spoiler](https://www.tibiawiki.com.br/wiki/Kilmaresh_Quest)
- [ ] **Grave Danger Quest** -- [Spoiler](https://www.tibiawiki.com.br/wiki/Grave_Danger_Quest)

**FEATURES**
- [ ] When you kill a Sheep you can't trade with any NPC in kilmaresh, you will need to pay a 1k fee to any guard in issavi city
- [ ] Naturally Sphinx and Crypt Warden fights with Cults in issavi [Like this](http://prntscr.com/oysxnj)

**Comment by ivansho92** [comment]
amazing work, we're waiting for this haha

**Comment by MajestyOTBR** [comment]
First part: https://github.com/opentibiabr/otservbr-global/commit/7ac964fed2d9bae41a323e1f2423fa60ba7ad140, thanks @lucaslking!
